### PR TITLE
added set operations and tests

### PR DESCRIPTION
**Pull request by grindhold**
this introduces all set operations.

### CODE REVIEW

**Comment by grindhold** [comment]
@nmelnick apparently my code does work for vala 0.34.1 but not for 0.22.x . Is such an old compiler version a hard requirement on this project?

**Comment by nmelnick** [comment]
@grindhold Thanks for the contribution! It looks like it compiles fine in 0.22.x. I usually target the lowest build supported by elements I use so those who are using OS-provided Vala aren't left out if they're on an old long-support release, though I'm not shy about bumping it up. The errors in Travis are due to the provided Redis being 3.0.x, where the count for SPOP came in Redis 3.2. That's a to-do for me, to have some feature flag support to enable/disable features depending on the server version. For now, I could alter .travis.yml to install a newer Redis.

This looks great -- and thank you for including tests. One minor thing, and I'd be happy to do it myself, but would you be willing to normalize your tabs to match the document, and add spaces between your operators? (ex: "count + 1" instead of "count+1"

**Comment by grindhold** [comment]
yup. no problem.

**Comment by grindhold** [comment]
also, all signs point to debian stretch becoming stable, soon. so the last operating system delivering 0.22.x should vanish ;) i think one can go for the future™ especially in a work-in-progress project

**Pull request merged**
